<?php

/**
 * Implement hook_theme()
*/

function yandex_weather_theme($existing, $type, $theme, $path){
	return array(
		'block_ya_weather' => array(
			'variables' => array(
				'result' => NUll,
			)	 
		),
		'field__node__field_solve_problems' => array(
			'variables' => array(
				'result' => NUll,
			)	 
		),		
	);
}


function template_preprocess_block_ya_weather(&$variables){

	//@true = значение ясной погоды
	//@false = значение дождливой погоды
	// источник https://yandex.ru/dev/weather/doc/dg/concepts/forecast-info.html
	$condition = array(
		'clear',
		'partly-cloudy',
		'cloudy',
		'overcast'
	);
	$fact = $variables['result']['fact']['condition'];
	
	if(in_array($fact, $condition)){
		$variables['fact_weather'] = TRUE;
	}

	//kint($variables);	
	
}

function template_preprocess_field__node__field_solve_problems(&$variables){


//kint($variables);

}

