<?php

/**
 * Implement hook_theme()
*/

function feedback_block_theme($existing, $type, $theme, $path){
	return array(
		'block_feedback_product' => array(
			'variables' => array(
				'result' => NUll,
			)	 
		)
	);
}

function template_preprocess_block_feedback_product(&$variables){
	foreach($variables['result'] as $key=>$value){
		$variables['feedback'][$key]['title'] = $value->get('title')->value;
		$text = strip_tags($value->get('body')->value);
		$number = strlen($text);
		if($number > 500){
			$variables['feedback'][$key]['body'] = substr($text,0 ,500)."...";
		}
		else{
			$variables['feedback'][$key]['body'] = $text;
		}
	}
}