<?php

use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implement hook_theme()
*/

function gallery_block_theme($existing, $type, $theme, $path){
	return array(
		'block_gallery_product' => array(
			'variables' => array(
				'result' => NUll,
			)	
		)
	);
}

function template_preprocess_block_gallery_product(&$variables){
	
	$i = 0;
	// Количесво выводимых фото на странице
	$number = 3;
	
	foreach($variables['result'] as $key=>$value){
		if($i < $number){
			$variables['photos'][$key]['image'] = $value['image'];
		}
	$i++;	
	}
}	 
